#!/usr/bin/env bash
# This script displays bad luck on 4th iteration, good luck on 8th, and Best School otherwise when its not on the 4th and 8th iteration and i understand that you want us to understand but its a bit streessing and there you have it !!
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done

