#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and catches SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
done

